include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    file_names: ignore
    must_be_immutable: ignore
    prefer_const_constructors: ignore
    prefer_const_literals_to_create_immutables: ignore
    prefer_typing_uninitialized_variables: ignore
    sized_box_for_whitespace: ignore
    sort_child_properties_last: ignore
